// CheckpointQuestion by kernel  2/12/2024
// a question of an course about println 

public class CheckpointQuestion 
{ // stat of the class
    public static void main(String args[])
    {// start of the main method
        System.out.println("0xKernel");// display my entire name 
        System.out.println("---------");// display dash 
        System.out.println("");// display nothing 

    }// end of the main method
} // end of the class