const s  = document.querySelector('.str1');
const s2 = document.querySelector('.str2');
const box= document.querySelector('.box');
const list = document.querySelector('.list');
const img = document.querySelector('img');
const count = document.querySelector('.count');
const count2 = document.querySelector('.count2');
const btn = document.querySelector('.btn');

// changer le txt
s.textContent = "Hy from JS";
s2.innerHTML = "Hy from <strong>JS</strong>";
// la difference entre innerText et textContent est que innerText ne prend pas en compte les balises html



const newEl = document.createElement('li');
newEl.innerText = "Generated by JS";
list.appendChild(newEl);
list.children[0].replaceWith(newEl);

img.src = "";

count.style.backgroundColor = "red";

count2.className = "foo";


count.classList.add('foo');
count.classList.remove('foo');

btn.addEventListener('click', () => {
    count.classList.toggle('foo');
}
);

const element = document.querySelector('.boxEL');

element.setAttribute('class', 'newclass');